<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends EntityRepository
{
    public function getByToken()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM AppBundle:User u ORDER BY u.id ASC'
            )
            ->getResult();
    }
}
