login:
    resource: '@AppBundle/Controller/LoginController.php'
    type: annotation
register:
    resource: '@AppBundle/Controller/RegisterController.php'
    type: annotation
app:
    resource: "@AppBundle/Controller/DefaultController.php"
    type:     annotation
client:
    resource: "@AppBundle/Controller/ClientController.php"
    type:     annotation