AppBundle\Entity\Client:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ClientRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        discount:
            type: float
            nullable: true
        discountCurrency:
            column: discount_currency
            type: text
            length: '16'
        creationDate:
            type: datetime
        name:
            type: text
            length: 255
        loginCount:
            type: integer
            options:
                default: 0
            column: login_count
        generatedOffersCount:
            type: integer
            options:
                default: 0
            column: generated_offers_count
    lifecycleCallbacks: {  }
