AppBundle\Entity\Hierarchy:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\HierarchyRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        idParent:
            type: integer
            column: id_parent
        name:
            type: text
            length: 255
        level:
            type: integer
        creationDate:
            type: datetime
            column: creation_date
    lifecycleCallbacks: {  }
    oneToMany:
        products:
            targetEntity: Product
            mappedBy: hierarchy
        products_sets:
            targetEntity: ProductsSet
            mappedBy: hierarchy