AppBundle\Entity\ProductsSetProduct:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ProductsSetProductRepository
    id:
        idProductSet:
            type: integer
            column: id_product_set
            id: true
        idProduct:
            type: integer
            column: id_product
    lifecycleCallbacks: {  }
