AppBundle\Entity\ProductsSet:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ProductsSetRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        number:
            type: text
            length: '64'
        type:
            type: text
            length: '64'
        idSystem:
            type: integer
            column: id_system
#        idSystemProvider:
#            type: integer
#            column: id_system_provider
        creationDate:
            type: datetime
            column: creation_date
    lifecycleCallbacks: {  }
    manyToMany:
        products:
            targetEntity: Product
            joinTable:
                name: product_set_product
                joinColumns:
                    id_product:
                        referencedColumnName: id
                inverseJoinColumns:
                    id_products_set:
                        referencedColumnName: id
