AppBundle\Entity\ProductsSet:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ProductsSetRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: text
            length: '128'
        number:
            type: text
            length: '64'

        exportCode:
            type: text
            length: '64'
            column: export_code
            nullable: true
        type:
            type: text
            length: '64'
        idSystem:
            type: integer
            column: id_system
            nullable: true
        image:
            type: text
            length: '64'
            nullable: true
        creationDate:
            type: datetime
            column: creation_date
    lifecycleCallbacks: {  }
    manyToOne:
        hierarchy:
            targetEntity: Hierarchy
            inversedBy: products_sets
            joinColumn:
                name: id_system
                referencedColumnName: id
    oneToMany:
        products:
            targetEntity: ProductInSet
            mappedBy: set
