AppBundle\Entity\Product:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ProductRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        code:
            type: text
            length: '64'
        exportCode:
            type: text
            length: '64'
            column: export_code
        name:
            type: text
            length: '64'
        image:
            type: text
            length: '64'
            nullable: true
        price:
            type: float
        currency:
            type: text
            length: '16'
        measureUnit:
            type: text
            length: '16'
            column: measure_unit
            nullable: true
        creationDate:
            type: datetime
            column: creation_date
    lifecycleCallbacks: {  }
    manyToOne:
        hierarchy:
            targetEntity: Hierarchy
            inversedBy: products
            joinColumn:
                name: hierarchy_id
                referencedColumnName: id
    manyToMany:
        products_sets:
            targetEntity: ProductsSet
            mappedBy: products