AppBundle\Entity\ProductsSet:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ProductsSetRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: text
            length: '128'
        number:
            type: text
            length: '64'
        type:
            type: text
            length: '64'
        idSystem:
            type: integer
            column: id_system
        image:
            type: text
            length: '64'
            nullable: true
#        idSystemProvider:
#            type: integer
#            column: id_system_provider
        creationDate:
            type: datetime
            column: creation_date
    lifecycleCallbacks: {  }
    manyToOne:
        hierarchy:
            targetEntity: Hierarchy
            inversedBy: products_sets
            joinColumn:
                name: id_system
                referencedColumnName: id
    manyToMany:
        products:
            targetEntity: Product
            inversedBy: products_sets
            joinTable:
                name: product_set_product
                joinColumns:
                    id_product:
                        referencedColumnName: id
                inverseJoinColumns:
                    id_products_set:
                        referencedColumnName: id
