AppBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        idClient:
            type: integer
            column: id_company
            nullable: true
        email:
            type: string
            length: 255
        role:
            type: string
            length: '32'
        discount:
            type: string
            length: '32'
            nullable: true
        password:
            type: string
            length: '128'
        lastLogin:
            type: datetime
            column: last_login
            nullable: true
        token:
            type: string
            length: '128'
            nullable: true
        tokenExpTime:
            type: datetime
            column: token_exp_time
        lastHost:
            type: string
            length: 255
            column: last_host
        creationDate:
            type: datetime
            column: creation_date
    lifecycleCallbacks: {  }
